/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: 3dhdscan (https://sketchfab.com/3dhdscan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wood-stick-02-0ab534c493e14f67bac01ee94f20e43f
Title: Wood Stick 02
*/

/*
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
 // const { nodes, materials } = useGLTF('/scene.gltf')
 const { nodes, materials } = useGLTF('../../public/car/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.698, -0.698, -4.228]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.008}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.wood_stick_02_wood_stick_02_0.geometry} material={materials.wood_stick_02} position={[0.013, -2.114, 0.71]} />
        </group>
      </group>
    </group>
  )
}

//useGLTF.preload('/scene.gltf')
useGLTF.preload('../../public/car/scene.gltf') */